version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: globant
      POSTGRES_PASSWORD: globant
      POSTGRES_DB: data
    ports:
      - "5432:5432"
    restart: always
    volumes: 
      - ./infra/init.sh:/docker-entrypoint-initdb.d/init.sh